### PR TITLE
Generic string bodies

### PR DESCRIPTION
**Pull request by octopus-prime**
Pull request for #536

### CODE REVIEW

File: test/http/doc_examples.cpp [hunk 1]
```diff
@@ -307,6 +311,50 @@ class doc_http_samples_test
         BEAST_EXPECTS(! ec, ec.message());
     }
 
+    void
+    doConstAndMutableBody()
+    {
+        test::pipe c{ios_};
```
Comment (vinniefalco) [inline test/http/doc_examples.cpp]: Wow yeah, you understand that `test::pipe` mumbo-jumbo and you even wrote the tests - this is great!

File: test/http/doc_examples.cpp [hunk 2]
```diff
@@ -307,6 +311,50 @@ class doc_http_samples_test
...
+
+        std::array<char, 15> const body {{"Hello, world!\n"}};
+        {
+            request<const_body<std::array<char, 15>>> req;
+            req.version = 11;
+            req.method(verb::put);
+            req.target("/");
+            req.body = body;
+            req.prepare_payload();
+            write(c.client, req);
```
Comment (vinniefalco) [inline test/http/doc_examples.cpp]: This is interesting because note that you are writing the null terminator into the body. That's one of the problems with using `std::array` as the body type, its always the same size.

File: example/common/const_body.hpp [hunk 3]
```diff
@@ -14,29 +14,21 @@
...
-        has_member_function_data<T, const typename T::value_type*, boost::mpl::vector<>, boost::function_types::const_qualified>::value
-    >;
+namespace detail {
+
+template<class T, class = void>
+struct is_const_container : std::false_type { };
+
+template< class T >
+struct is_const_container<T, beast::detail::void_t<
+    decltype( std::declval<T&>().size() ),
```
Comment (vinniefalco) [inline example/common/const_body.hpp]: Nice job on the traits! @pdimov showed me this trick for checking the return value:
```
    std::declval<std::size_t&>() = std::declval<T&>().size()
```

You can do something similar for checking the return value of `data`. 
```
    std::declval<std::void const*&>() = std::declval<T&>().data()
```

File: example/common/mutable_body.hpp [hunk 4]
```diff
@@ -14,33 +14,23 @@
 #include <beast/core/detail/type_traits.hpp>
 #include <boost/asio/buffer.hpp>
 #include <boost/optional.hpp>
-#include <boost/tti/has_type.hpp>
-#include <boost/tti/has_member_function.hpp>
-#include <boost/mpl/identity.hpp>
```
Comment (vinniefalco) [inline example/common/mutable_body.hpp]: Thank you for not dragging TTI and MPL into Beast.. lol

File: example/common/const_body.hpp [hunk 5]
```diff
@@ -39,7 +39,7 @@ template <typename Container>
 struct const_body
 {
     static_assert(sizeof(typename Container::value_type) == 1, "Const character requirements not met");
-    static_assert(detail::is_const_container<Container>::value, "Const container requirements2 not met");
+    static_assert(detail::is_const_container<Container>::value, "Const container requirements not met");
```
Comment (vinniefalco) [inline example/common/const_body.hpp]: I would use the names **ConstContainer** and **MutableContainer** since those are suggestive of the concept requirements.

File: test/http/doc_examples.cpp [hunk 6]
```diff
@@ -351,10 +351,41 @@ class doc_http_samples_test
...
+            BEAST_EXPECTS(res.body == std::vector<char>(body.begin(), body.end()),
+                std::string(body.begin(), body.end()));
         }
     }
 
+    void
+	checkConstBody()
+    {
+    	BEAST_EXPECTS(::detail::is_const_container<std::string>::value == true,
+    	    "is_const_container<std::string>::value");
```
Comment (vinniefalco) [inline test/http/doc_examples.cpp]: Consider this instead:
```
BOOST_STATIC_ASSERT(::detail::is_const_container<std::string>::value);
```

File: example/common/const_body.hpp [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
+//
+
+#ifndef BEAST_EXAMPLE_COMMON_CONST_BODY_HPP_
+#define BEAST_EXAMPLE_COMMON_CONST_BODY_HPP_
+
+#include <beast/config.hpp>
+#include <beast/http/error.hpp>
+#include <beast/http/message.hpp>
+#include <beast/core/detail/type_traits.hpp>
```
Comment (vinniefalco) [inline example/common/const_body.hpp]: Is this needed?

**Comment by vinniefalco** [comment]
This should be rebased against **v68**, and you  should add the files `const_body.cpp` and `mutable_body.cpp` to this project:
https://github.com/vinniefalco/Beast/tree/v68/test/common

The .cpp file just includes the .hpp, to make sure it compiles by itself. Here's an example
https://github.com/vinniefalco/Beast/blob/v68/test/common/detect_ssl.cpp

File: test/http/doc_examples.cpp (hunk 2 above)
Comment (octopus-prime) [inline test/http/doc_examples.cpp]: Something to do here? Replace 15 by 14?

File: example/common/const_body.hpp (hunk 3 above)
Comment (octopus-prime) [inline example/common/const_body.hpp]: willfix

File: test/http/doc_examples.cpp (hunk 6 above)
Comment (octopus-prime) [inline test/http/doc_examples.cpp]: yeah! willfix

File: example/common/const_body.hpp (hunk 7 above)
Comment (octopus-prime) [inline example/common/const_body.hpp]: not sure. will check it

File: test/http/doc_examples.cpp (hunk 2 above)
Comment (vinniefalco) [inline test/http/doc_examples.cpp]: Nothing to do here except to note that people using `std::array` need to be careful because the entire array will be written out no matter how big the string is.

**Comment by octopus-prime** [comment]
After rebasing my branch i have to close this pull request and create a new one?!
Is my branch rebased? github says while comparing against v68 "These branches can be automatically merged."

**Comment by vinniefalco** [comment]
Github often gets confused when projects attempt to keep a linear history, I wouldn't worry about it. But you included a merge commit which I typically try to avoid. Don't worry I will l fix it up.

**Comment by octopus-prime** [comment]
After rebasing i get bad errors:

```
In file included from /home/mike/workspace/Beast/include/beast/http.hpp:21:0,
                 from /home/mike/workspace/Beast/include/beast.hpp:14,
                 from /home/mike/workspace/Beast/./example/doc/http_examples.hpp:8,
                 from /home/mike/workspace/Beast/test/http/doc_examples.cpp:8:
/home/mike/workspace/Beast/include/beast/http/parser.hpp: In instantiation of ‘class beast::http::parser<true, mutable_body<std::vector<char> >, std::allocator<char> >’:
/home/mike/workspace/Beast/test/http/doc_examples.cpp:336:65:   required from here
/home/mike/workspace/Beast/include/beast/http/parser.hpp:52:5: error: static assertion failed: BodyWriter requirements not met
     static_assert(is_body_writer<Body>::value,
     ^~~~~~~~~~~~~
```

Any idea why body concept check stopped working?

**Comment by octopus-prime** [comment]
I followed your suggestions. So you can try another review.

**Comment by vinniefalco** [comment]
Code looks great, I squashed it down and now its part of version 68 (see https://github.com/vinniefalco/Beast/pull/541) Thanks!
