### ISSUE TITLE
Build error on raspberry pi

### ISSUE THREAD

**Issue by amitv87** [vinniefalco/Beast#81]
I get missing  **boost/endian/buffers.hpp**, not sure if there is boost module for this
I installed boost with this command **sudo apt-get install libboost-all-dev **
~~~
In file included from Beast/include/beast/websocket/detail/stream_base.hpp:14:0,
				Beast/include/beast/websocket/option.hpp:12,
				Beast/include/beast/websocket.hpp:12,
				Beast/examples/websocket_example.cpp:9:
Beast/include/beast/websocket/detail/frame.hpp:18:36: fatal error: boost/endian/buffers.hpp: No such file or directory
 #include <boost/endian/buffers.hpp>
~~~

**Comment by amitv87** [comment]
Oops only works with 1.58+
