### ISSUE TITLE
Compile fails with MS Visual C++ 2015

### ISSUE THREAD

**Issue by daniele77** [vinniefalco/Beast#267]
When compiling the examples with Visual C++ 2015, I get the following error:
`Compiler Error C2899: "typename cannot be used outside a template declaration"`
in file:
`Beast\include\beast/http/detail/basic_fields.hpp`
at lines: 97, 100, 142.

I tried with the current git master HEAD: commit 9f10b11

The code compiles with VS 2015, gcc 4.9.2 and clang 3.5.0 if I remove "typename" from the lines 97, 100, 142.

**Comment by vinniefalco** [comment]
That is bizarre because I am on Visual Studio 2015. I suspect you are using something earlier than VS 2015 Update 3. However, since the `typename` is not technically necessary (since the class is not a template class) I will remove it. Thanks for the report!

**Comment by daniele77** [comment]
Thanks, I realized I had VS without updates. I'm gonna update it with update 3.
Anyway: as you said, typename was not strictly necessary in that case.
